# Generated by Django 3.0.3 on 2020-04-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='type name', max_length=50)),
                ('size_variant', models.CharField(choices=[('single', 'single'), ('double', 'double')], default='single', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_cheese', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_small_0_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_small_1_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_small_2_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_small_3_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_small_4_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_large_0_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_large_1_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_large_2_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_large_3_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_large_4_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_small_0_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_small_1_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_small_2_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_small_3_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_small_4_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_large_0_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_large_1_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_large_2_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_large_3_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_large_4_toppings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='item name', max_length=50)),
                ('is_sub', models.BooleanField(default=False)),
                ('price_single', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('price_small', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('price_large', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealType', to='menu.MealType')),
            ],
        ),
    ]
