# Generated by Django 3.0.3 on 2020-04-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
