# Generated by Django 3.0.3 on 2020-04-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_topping_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topping',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
