# Generated by Django 3.0.3 on 2020-04-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200422_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtype',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
