# Generated by Django 3.0.3 on 2020-04-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtype',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
