# Generated by Django 3.0.3 on 2020-05-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20200425_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='default_item.png', help_text='AA help text', upload_to=''),
        ),
    ]
