# Generated by Django 3.0.3 on 2020-05-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20200502_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtype',
            name='image',
            field=models.ImageField(blank=True, default='default_item.png', upload_to='media/'),
        ),
    ]
