# Generated by Django 3.0.3 on 2020-05-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_mealtype_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_large_0_toppings',
            new_name='neapolitan_large_0_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_large_1_toppings',
            new_name='neapolitan_large_1_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_large_2_toppings',
            new_name='neapolitan_large_2_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_large_3_toppings',
            new_name='neapolitan_large_3_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_large_4_toppings',
            new_name='neapolitan_large_4_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_small_0_toppings',
            new_name='neapolitan_small_0_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_small_1_toppings',
            new_name='neapolitan_small_1_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_small_2_toppings',
            new_name='neapolitan_small_2_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_small_3_toppings',
            new_name='neapolitan_small_3_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_small_4_toppings',
            new_name='neapolitan_small_4_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_large_0_toppings',
            new_name='sicilian_large_0_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_large_1_toppings',
            new_name='sicilian_large_1_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_large_2_toppings',
            new_name='sicilian_large_2_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_large_3_toppings',
            new_name='sicilian_large_3_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_large_4_toppings',
            new_name='sicilian_large_4_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_small_0_toppings',
            new_name='sicilian_small_0_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_small_1_toppings',
            new_name='sicilian_small_1_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_small_2_toppings',
            new_name='sicilian_small_2_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_small_3_toppings',
            new_name='sicilian_small_3_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_small_4_toppings',
            new_name='sicilian_small_4_toppings',
        ),
    ]
