# Generated by Django 3.0.3 on 2020-03-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='itemId',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
