# Generated by Django 3.0.3 on 2020-03-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cartitem_itemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='pizzaFrom',
            field=models.CharField(choices=[('napolitana', 'napolitana'), ('siciliana', 'siciliana')], default='not pizza', max_length=10),
        ),
    ]
