# Generated by Django 3.0.3 on 2020-03-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cartitem_pizzafrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='pizzaFrom',
            field=models.CharField(choices=[('napolitana', 'napolitana'), ('siciliana', 'siciliana'), ('not pizza', 'not pizza')], default='not pizza', max_length=10),
        ),
    ]
