# Generated by Django 3.0.3 on 2020-03-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cartitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='pizzaFrom',
            new_name='pizzaForm',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='extraCheese',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pizzaToppings',
            field=models.IntegerField(default=0),
        ),
    ]
