# Generated by Django 3.0.3 on 2020-03-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200318_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_cheese', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_small_cheese', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_small_1_topping', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_small_2_topping', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_small_3_topping', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_small_special', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_large_cheese', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_large_1_topping', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_large_2_topping', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_large_3_topping', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('napolitana_large_special', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_small_cheese', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_small_1_topping', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_small_2_topping', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_small_3_topping', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_small_special', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_large_cheese', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_large_1_topping', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_large_2_topping', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_large_3_topping', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('siciliana_large_special', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='extraCheese',
            field=models.BooleanField(default=False),
        ),
    ]
