# Generated by Django 3.0.3 on 2020-03-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200319_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='toppings',
            field=models.IntegerField(default=0),
        ),
    ]
