# Generated by Django 3.0.3 on 2020-03-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_cartitem_toppings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_large_1_topping',
            new_name='napolitana_large_0_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_large_2_topping',
            new_name='napolitana_large_1_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_large_3_topping',
            new_name='napolitana_large_2_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_large_cheese',
            new_name='napolitana_large_3_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_large_special',
            new_name='napolitana_large_4_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_small_1_topping',
            new_name='napolitana_small_0_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_small_2_topping',
            new_name='napolitana_small_1_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_small_3_topping',
            new_name='napolitana_small_2_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_small_cheese',
            new_name='napolitana_small_3_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='napolitana_small_special',
            new_name='napolitana_small_4_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_large_1_topping',
            new_name='siciliana_large_0_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_large_2_topping',
            new_name='siciliana_large_1_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_large_3_topping',
            new_name='siciliana_large_2_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_large_cheese',
            new_name='siciliana_large_3_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_large_special',
            new_name='siciliana_large_4_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_small_1_topping',
            new_name='siciliana_small_0_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_small_2_topping',
            new_name='siciliana_small_1_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_small_3_topping',
            new_name='siciliana_small_2_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_small_cheese',
            new_name='siciliana_small_3_toppings',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='siciliana_small_special',
            new_name='siciliana_small_4_toppings',
        ),
    ]
