# Generated by Django 3.0.3 on 2020-03-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200319_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='itemId',
            field=models.IntegerField(default=0),
        ),
    ]
