# Generated by Django 3.0.3 on 2020-03-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price',
            new_name='priceUnit',
        ),
    ]
