# Generated by Django 3.0.3 on 2020-03-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200320_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price',
            new_name='priceUnit',
        ),
    ]
