# Generated by Django 3.0.3 on 2020-03-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200320_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='priceTotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
