# Generated by Django 3.0.3 on 2020-03-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_cartitem_pricetotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='toppings',
        ),
    ]
