# Generated by Django 3.0.3 on 2020-04-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_cartitem_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
