# Generated by Django 3.0.3 on 2020-04-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
