# Generated by Django 3.0.3 on 2020-04-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0020_delete_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='extraCheese',
            new_name='extra_cheese',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='pizzaForm',
            new_name='pizza_form',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='priceTotal',
            new_name='price_total',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='itemId',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='priceUnit',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='type',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.MenuItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='ordered_items', to='orders.CartItem'),
        ),
    ]
