# Generated by Django 3.0.3 on 2020-04-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0021_auto_20200421_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.MenuItem'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(choices=[('single', 'single'), ('small', 'small'), ('large', 'large')], max_length=6),
        ),
    ]
