# Generated by Django 3.0.3 on 2020-04-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200421_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
