# Generated by Django 3.0.3 on 2020-05-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_cartitem_price_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='pizza_form',
            field=models.CharField(choices=[('neapolitan', 'neapolitan'), ('sicilian', 'sicilian'), ('not pizza', 'not pizza')], default='not pizza', max_length=10),
        ),
    ]
