# Generated by Django 3.0.7 on 2020-06-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20200510_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='pizza_form',
            field=models.CharField(choices=[('neapolitan', 'neapolitan'), ('sicilian', 'sicilian'), ('not pizza', 'not pizza')], default='not pizza', max_length=10),
        ),
    ]
